// Code generated by MockGen. DO NOT EDIT.
// Source: ./router.go

// Package infrahttp is a generated GoMock package.
package infrahttp

import (
	gomock "github.com/golang/mock/gomock"
	http "net/http"
	reflect "reflect"
)

// MockRouter is a mock of Router interface
type MockRouter struct {
	ctrl     *gomock.Controller
	recorder *MockRouterMockRecorder
}

// MockRouterMockRecorder is the mock recorder for MockRouter
type MockRouterMockRecorder struct {
	mock *MockRouter
}

// NewMockRouter creates a new mock instance
func NewMockRouter(ctrl *gomock.Controller) *MockRouter {
	mock := &MockRouter{ctrl: ctrl}
	mock.recorder = &MockRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRouter) EXPECT() *MockRouterMockRecorder {
	return m.recorder
}

// GetHandler mocks base method
func (m *MockRouter) GetHandler() http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHandler")
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// GetHandler indicates an expected call of GetHandler
func (mr *MockRouterMockRecorder) GetHandler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHandler", reflect.TypeOf((*MockRouter)(nil).GetHandler))
}

// HandleFunc mocks base method
func (m *MockRouter) HandleFunc(path string, f func(http.ResponseWriter, *http.Request)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleFunc", path, f)
}

// HandleFunc indicates an expected call of HandleFunc
func (mr *MockRouterMockRecorder) HandleFunc(path, f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleFunc", reflect.TypeOf((*MockRouter)(nil).HandleFunc), path, f)
}

// GetRouteParams mocks base method
func (m *MockRouter) GetRouteParams(r *http.Request) map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRouteParams", r)
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetRouteParams indicates an expected call of GetRouteParams
func (mr *MockRouterMockRecorder) GetRouteParams(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRouteParams", reflect.TypeOf((*MockRouter)(nil).GetRouteParams), r)
}
